### ISSUE TITLE
Registering Package

### ISSUE THREAD

**Issue by p-casgrain** [krynju/AVLTrees.jl#1]
Is there any chance that this package can be registered to the general Julia package registry? For example, this would allow the package to be listed by `Pkg` and to become a dependency for other projects. Instructions on registering a package [can be found here](https://github.com/JuliaRegistries/Registrator.jl#via-the-web-interface), and it shouldn't take more than a few minutes to complete.

**Comment by krynju** [comment]
Hey! 
I wanted to do it after implementing a Set and Dict interface for this at some point.
But I can definitely do it right now if you find the package any useful as is.

Examples of usage are in the test suite, should be pretty straightforward

**Comment by p-casgrain** [comment]
Thanks for the quick reply!
I've also written some more Base functions for your implementation such as ` haskey, getkey, getindex, setindex!, length, isempty, popfirst!, insert!, delete!, first_index`. I will branch and make a pull req at some point soon.

What else would we need for full Dict interface?

-P

**Comment by krynju** [comment]
Submitted the package registration, should be registered this week I think 

Great! Not sure what is missing currently since it's been a while, but the goal is to provide the same interace as the Base Dict. Same with Set, which now I see was somewhat implemented by me, but it's most likely far from complete. 

Functionality wise the low level interface of tree and node should be complete, so implementation of Set and Dict should be just a matter of matching the higher level interface with the low level one.

**Comment by p-casgrain** [comment]
> Submitted the package registration, should be registered this week I think
Awesome! Thanks!

> Functionality wise the low level interface of tree and node should be complete, so implementation of Set and Dict should be just a matter of matching the higher level interface with the low level one.
I believe it is as well. I haven't used AVLSet as of yet but I think that I should have a complete Dict interface soon enough.

This is another more subtle point: I think that the size(...) function should be renamed to length since it implies multiple axes.

**Comment by krynju** [comment]
Closing as the PR for registry was merged and Pkg install was successful on my env.

Please put the other ideas in separate issues, so discussion can be tracked under them
